"""initial schema

Revision ID: c37d40824f3a
Revises: 
Create Date: 2026-02-17 16:59:31.856233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c37d40824f3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boq_catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('section', sa.Enum('product', 'service', 'griptel', 'solar', name='catalog_section'), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('ordering_hints', sa.Text(), nullable=True),
    sa.Column('product_category', sa.String(length=200), nullable=False),
    sa.Column('product_subcategory', sa.String(length=200), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_index', 'sheet_name', name='uq_catalog_row_sheet')
    )
    op.create_index(op.f('ix_boq_catalog_product_code'), 'boq_catalog', ['product_code'], unique=False)
    op.create_index('ix_catalog_product_category', 'boq_catalog', ['product_category'], unique=False)
    op.create_index('ix_catalog_search', 'boq_catalog', ['product_code', 'description', 'product_category'], unique=False)
    op.create_index('ix_catalog_section', 'boq_catalog', ['section'], unique=False)
    op.create_table('dependency_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('catalog_product_code', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_rules_catalog_product_code'), 'dependency_rules', ['catalog_product_code'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.String(length=100), nullable=False),
    sa.Column('site_name', sa.String(length=300), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_boq_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=True),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rule_applied', sa.Text(), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['boq_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_boq_items_catalog_item_id'), 'project_boq_items', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_project_boq_items_project_id'), 'project_boq_items', ['project_id'], unique=False)
    op.create_table('project_tssr',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.String(length=100), nullable=False),
    sa.Column('site_name', sa.String(length=300), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('config_string', sa.String(length=50), nullable=False),
    sa.Column('sectors', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('sector_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('site_category', sa.String(length=50), nullable=False),
    sa.Column('landlord_name', sa.String(length=300), nullable=False),
    sa.Column('access_instructions', sa.Text(), nullable=False),
    sa.Column('crane_needed', sa.Boolean(), nullable=False),
    sa.Column('cabinet_type', sa.String(length=50), nullable=False),
    sa.Column('acdb', sa.String(length=100), nullable=False),
    sa.Column('rectifier', sa.String(length=100), nullable=False),
    sa.Column('earthing', sa.String(length=100), nullable=False),
    sa.Column('hse_hazards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roof_type', sa.String(length=100), nullable=True),
    sa.Column('roof_material', sa.String(length=100), nullable=True),
    sa.Column('roof_load', sa.Float(), nullable=True),
    sa.Column('tower_height', sa.Float(), nullable=True),
    sa.Column('cable_ladder_length', sa.Float(), nullable=True),
    sa.Column('vertical_cable_route', sa.Float(), nullable=True),
    sa.Column('mount_type', sa.String(length=100), nullable=False),
    sa.Column('painting_required', sa.Boolean(), nullable=False),
    sa.Column('painting_color', sa.String(length=100), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tssr')
    op.drop_index(op.f('ix_project_boq_items_project_id'), table_name='project_boq_items')
    op.drop_index(op.f('ix_project_boq_items_catalog_item_id'), table_name='project_boq_items')
    op.drop_table('project_boq_items')
    op.drop_table('projects')
    op.drop_index(op.f('ix_dependency_rules_catalog_product_code'), table_name='dependency_rules')
    op.drop_table('dependency_rules')
    op.drop_index('ix_catalog_section', table_name='boq_catalog')
    op.drop_index('ix_catalog_search', table_name='boq_catalog')
    op.drop_index('ix_catalog_product_category', table_name='boq_catalog')
    op.drop_index(op.f('ix_boq_catalog_product_code'), table_name='boq_catalog')
    op.drop_table('boq_catalog')
    # ### end Alembic commands ###
